<?php

use Livewire\Volt\Component;
use App\Models\Payslip;

new class extends Component {
    public Payslip $payslip;
    
    public function mount(Payslip $payslip)
    {
        $this->payslip = $payslip->load(['teacher', 'generatedBy', 'sessions.class.course', 'sessions.attendances']);
    }
    
    public function finalize()
    {
        try {
            $this->payslip->finalize();
            session()->flash('success', 'Payslip has been finalized.');
            return redirect()->route('admin.payslips.show', $this->payslip);
        } catch (\Exception $e) {
            session()->flash('error', 'Failed to finalize payslip: ' . $e->getMessage());
        }
    }
    
    public function revertToDraft()
    {
        try {
            $this->payslip->revertToDraft();
            session()->flash('success', 'Payslip has been reverted to draft.');
            return redirect()->route('admin.payslips.show', $this->payslip);
        } catch (\Exception $e) {
            session()->flash('error', 'Failed to revert payslip: ' . $e->getMessage());
        }
    }
    
    public function markAsPaid()
    {
        try {
            $this->payslip->markAsPaid();
            session()->flash('success', 'Payslip has been marked as paid.');
            return redirect()->route('admin.payslips.show', $this->payslip);
        } catch (\Exception $e) {
            session()->flash('error', 'Failed to mark payslip as paid: ' . $e->getMessage());
        }
    }
    
    public function deletePayslip()
    {
        if (! $this->payslip->canBeEdited()) {
            session()->flash('error', 'Only draft payslips can be deleted.');
            return;
        }
        
        try {
            // Reset all sessions' payout status
            foreach ($this->payslip->sessions as $session) {
                $session->update(['payout_status' => 'unpaid']);
            }
            
            $teacherName = $this->payslip->teacher->name;
            $month = $this->payslip->formatted_month;
            
            $this->payslip->delete();
            
            session()->flash('success',"Payslip for {$teacherName} ({$month}) has been deleted.");
            return redirect()->route('admin.payslips.index');
        } catch (\Exception $e) {
            session()->flash('error', 'Failed to delete payslip: ' . $e->getMessage());
        }
    }
};

?>

<div>
    <div class="mb-6 flex items-center justify-between">
        <div>
            <flux:heading size="xl">{{ $payslip->teacher->name }} - {{ $payslip->formatted_month }}</flux:heading>
            <flux:text class="mt-2">Payslip Details and Session Information</flux:text>
        </div>
        <div class="flex items-center gap-3">
            @if($payslip->canBeEdited())
                <flux:button variant="outline" href="{{ route('admin.payslips.edit', $payslip) }}" wire:navigate>
                    <div class="flex items-center justify-center">
                        <flux:icon name="pencil" class="w-4 h-4 mr-1" />
                        Edit Payslip
                    </div>
                </flux:button>
            @endif
            
            <flux:button variant="outline" href="{{ route('admin.payslips.index') }}" wire:navigate>
                <div class="flex items-center justify-center">
                    <flux:icon name="chevron-left" class="w-4 h-4 mr-1" />
                    Back to Payslips
                </div>
            </flux:button>
        </div>
    </div>

    <!-- Payslip Summary Card -->
    <flux:card class="mb-6">
        <flux:heading size="lg" class="mb-4">Payslip Summary</flux:heading>
        
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <div>
                <flux:text variant="muted" size="sm">Status</flux:text>
                <div class="mt-1">
                    <flux:badge variant="{{ $payslip->status === 'paid' ? 'positive' : ($payslip->status === 'finalized' ? 'primary' : 'warning') }}">
                        {{ $payslip->status_label }}
                    </flux:badge>
                </div>
            </div>
            
            <div>
                <flux:text variant="muted" size="sm">Total Sessions</flux:text>
                <flux:heading size="lg" class="mt-1">{{ $payslip->total_sessions }}</flux:heading>
            </div>
            
            <div>
                <flux:text variant="muted" size="sm">Total Amount</flux:text>
                <flux:heading size="lg" class="mt-1">RM{{ number_format($payslip->total_amount, 2) }}</flux:heading>
            </div>
            
            <div>
                <flux:text variant="muted" size="sm">Generated By</flux:text>
                <flux:text class="mt-1">{{ $payslip->generatedBy->name }}</flux:text>
                <flux:text variant="muted" size="sm">{{ $payslip->generated_at->format('M d, Y g:i A') }}</flux:text>
            </div>
        </div>
        
        @if($payslip->finalized_at)
            <div class="mt-4 pt-4 border-t border-gray-200">
                <flux:text variant="muted" size="sm">Finalized on {{ $payslip->finalized_at->format('M d, Y g:i A') }}</flux:text>
            </div>
        @endif
        
        @if($payslip->paid_at)
            <div class="mt-2">
                <flux:text variant="muted" size="sm">Paid on {{ $payslip->paid_at->format('M d, Y g:i A') }}</flux:text>
            </div>
        @endif
        
        @if($payslip->notes)
            <div class="mt-4 pt-4 border-t border-gray-200">
                <flux:text variant="muted" size="sm">Notes</flux:text>
                <flux:text class="mt-1">{{ $payslip->notes }}</flux:text>
            </div>
        @endif
    </flux:card>

    <!-- Teacher Information Card -->
    <flux:card class="mb-6">
        <flux:heading size="lg" class="mb-4">Teacher Information</flux:heading>
        
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
                <flux:text variant="muted" size="sm">Full Name</flux:text>
                <flux:text class="mt-1">{{ $payslip->teacher->name }}</flux:text>
            </div>
            
            <div>
                <flux:text variant="muted" size="sm">Email</flux:text>
                <flux:text class="mt-1">{{ $payslip->teacher->email }}</flux:text>
            </div>
            
            @if($payslip->teacher->teacher)
                <div>
                    <flux:text variant="muted" size="sm">Teacher ID</flux:text>
                    <flux:text class="mt-1">{{ $payslip->teacher->teacher->teacher_id ?? 'N/A' }}</flux:text>
                </div>
                
                <div>
                    <flux:text variant="muted" size="sm">Phone</flux:text>
                    <flux:text class="mt-1">{{ $payslip->teacher->teacher->phone ?? 'N/A' }}</flux:text>
                </div>
            @endif
        </div>
        
        <div class="mt-4 pt-4 border-t border-gray-200">
            <flux:button variant="outline" href="{{ route('teachers.show', $payslip->teacher) }}" wire:navigate>
                <div class="flex items-center justify-center">
                    <flux:icon name="user" class="w-4 h-4 mr-1" />
                    View Teacher Profile
                </div>
            </flux:button>
        </div>
    </flux:card>

    <!-- Sessions Details Card -->
    <flux:card class="mb-6">
        <flux:heading size="lg" class="mb-4">Session Details ({{ $payslip->sessions->count() }} sessions)</flux:heading>
        
        @if($payslip->sessions->count() > 0)
            <div class="overflow-x-auto">
                <table class="w-full">
                    <thead>
                        <tr class="border-b border-gray-200">
                            <th class="text-left py-3 px-4">Date & Time</th>
                            <th class="text-left py-3 px-4">Course & Class</th>
                            <th class="text-left py-3 px-4">Students</th>
                            <th class="text-left py-3 px-4">Present</th>
                            <th class="text-right py-3 px-4">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($payslip->sessions as $session)
                            <tr class="border-b border-gray-100">
                                <td class="py-3 px-4">
                                    <flux:text>{{ $session->session_date->format('M d, Y') }}</flux:text>
                                    <flux:text variant="muted" size="sm" class="block">{{ $session->session_time->format('g:i A') }}</flux:text>
                                </td>
                                <td class="py-3 px-4">
                                    <flux:text>{{ $session->class->course->name }}</flux:text>
                                    <flux:text variant="muted" size="sm" class="block">{{ $session->class->title }}</flux:text>
                                </td>
                                <td class="py-3 px-4">
                                    <flux:text>{{ $session->attendances->count() }}</flux:text>
                                </td>
                                <td class="py-3 px-4">
                                    <flux:text>{{ $session->attendances->where('status', 'present')->count() }}</flux:text>
                                </td>
                                <td class="py-3 px-4 text-right">
                                    <flux:text>RM{{ number_format($session->allowance_amount ?? 0, 2) }}</flux:text>
                                </td>
                            </tr>
                        @endforeach
                        
                        <tr class="bg-gray-50  font-semibold">
                            <td colspan="4" class="py-3 px-4 text-right">
                                <flux:text>Total Amount:</flux:text>
                            </td>
                            <td class="py-3 px-4 text-right">
                                <flux:text>RM{{ number_format($payslip->total_amount, 2) }}</flux:text>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        @else
            <div class="text-center py-8">
                <flux:icon name="calendar" class="w-12 h-12 mx-auto text-gray-400 mb-4" />
                <flux:text variant="muted">No sessions found for this payslip.</flux:text>
            </div>
        @endif
    </flux:card>

    <!-- Actions Card -->
    <flux:card>
        <flux:heading size="lg" class="mb-4">Actions</flux:heading>
        
        <div class="flex flex-wrap gap-3">
            @if($payslip->canBeFinalized())
                <flux:button variant="primary" wire:click="finalize" wire:confirm="Are you sure you want to finalize this payslip? This action cannot be undone.">
                    <div class="flex items-center justify-center">
                        <flux:icon name="check" class="w-4 h-4 mr-1" />
                        Finalize Payslip
                    </div>
                </flux:button>
            @endif
            
            @if($payslip->isFinalized())
                <flux:button variant="primary" wire:click="markAsPaid" wire:confirm="Are you sure you want to mark this payslip as paid?">
                    <div class="flex items-center justify-center">
                        <flux:icon name="banknotes" class="w-4 h-4 mr-1" />
                        Mark as Paid
                    </div>
                </flux:button>
                
                <flux:button variant="outline" wire:click="revertToDraft" wire:confirm="Are you sure you want to revert this payslip to draft status?">
                    <div class="flex items-center justify-center">
                        <flux:icon name="arrow-left" class="w-4 h-4 mr-1" />
                        Revert to Draft
                    </div>
                </flux:button>
            @endif
            
            @if($payslip->canBeEdited())
                <flux:button variant="danger" wire:click="deletePayslip" wire:confirm="Are you sure you want to delete this payslip? This action cannot be undone and will reset all session payout statuses.">
                    <div class="flex items-center justify-center">
                        <flux:icon name="trash" class="w-4 h-4 mr-1" />
                        Delete Payslip
                    </div>
                </flux:button>
            @endif
        </div>
        
        @if(!$payslip->canBeEdited() && !$payslip->canBeFinalized() && !$payslip->isFinalized())
            <div class="mt-4 p-4 bg-blue-50 /20 rounded-lg">
                <flux:text variant="muted" size="sm">This payslip has been paid and cannot be modified.</flux:text>
            </div>
        @endif
    </flux:card>
</div>