import {
  AlignLeft,
  Calendar,
  CalendarClock,
  CheckSquare,
  CircleCheck,
  FileText,
  Hash,
  Heading2,
  Link2,
  ListChecks,
  Mail,
  Paperclip,
  Phone,
  Type,
} from 'lucide-react';

const nextId = (prefix) => `${prefix}_${Math.random().toString(36).slice(2, 8)}`;

export const FIELD_TYPES = [
  {
    type: 'text',
    label: 'Short text',
    group: 'Text',
    icon: Type,
    isData: true,
    defaultSettings: () => ({
      id: nextId('f'),
      type: 'text',
      label: 'New field',
      required: false,
    }),
  },
  {
    type: 'textarea',
    label: 'Long text',
    group: 'Text',
    icon: FileText,
    isData: true,
    defaultSettings: () => ({
      id: nextId('f'),
      type: 'textarea',
      label: 'New field',
      required: false,
      rows: 4,
    }),
  },
  {
    type: 'email',
    label: 'Email',
    group: 'Text',
    icon: Mail,
    isData: true,
    defaultSettings: () => ({
      id: nextId('f'),
      type: 'email',
      label: 'Email',
      required: true,
      role: 'email',
    }),
  },
  {
    type: 'phone',
    label: 'Phone',
    group: 'Text',
    icon: Phone,
    isData: true,
    defaultSettings: () => ({
      id: nextId('f'),
      type: 'phone',
      label: 'Phone',
      required: false,
      role: 'phone',
    }),
  },
  {
    type: 'number',
    label: 'Number',
    group: 'Text',
    icon: Hash,
    isData: true,
    defaultSettings: () => ({
      id: nextId('f'),
      type: 'number',
      label: 'Number',
      required: false,
    }),
  },
  {
    type: 'url',
    label: 'URL',
    group: 'Text',
    icon: Link2,
    isData: true,
    defaultSettings: () => ({
      id: nextId('f'),
      type: 'url',
      label: 'URL',
      required: false,
    }),
  },
  {
    type: 'select',
    label: 'Dropdown',
    group: 'Choice',
    icon: ListChecks,
    isData: true,
    defaultSettings: () => ({
      id: nextId('f'),
      type: 'select',
      label: 'Dropdown',
      required: false,
      options: [{ label: 'Option 1', value: 'opt_1' }],
    }),
  },
  {
    type: 'radio',
    label: 'Single choice',
    group: 'Choice',
    icon: CircleCheck,
    isData: true,
    defaultSettings: () => ({
      id: nextId('f'),
      type: 'radio',
      label: 'Single choice',
      required: false,
      options: [{ label: 'Option 1', value: 'opt_1' }],
    }),
  },
  {
    type: 'checkbox_group',
    label: 'Multi choice',
    group: 'Choice',
    icon: CheckSquare,
    isData: true,
    defaultSettings: () => ({
      id: nextId('f'),
      type: 'checkbox_group',
      label: 'Multi choice',
      required: false,
      options: [{ label: 'Option 1', value: 'opt_1' }],
    }),
  },
  {
    type: 'file',
    label: 'File upload',
    group: 'Other',
    icon: Paperclip,
    isData: true,
    defaultSettings: () => ({
      id: nextId('f'),
      type: 'file',
      label: 'Upload',
      required: false,
      role: 'resume',
      accept: ['pdf'],
      max_size_kb: 5120,
    }),
  },
  {
    type: 'date',
    label: 'Date',
    group: 'Other',
    icon: Calendar,
    isData: true,
    defaultSettings: () => ({
      id: nextId('f'),
      type: 'date',
      label: 'Date',
      required: false,
    }),
  },
  {
    type: 'datetime',
    label: 'Date & time',
    group: 'Other',
    icon: CalendarClock,
    isData: true,
    defaultSettings: () => ({
      id: nextId('f'),
      type: 'datetime',
      label: 'Date & time',
      required: false,
    }),
  },
  {
    type: 'heading',
    label: 'Heading',
    group: 'Display',
    icon: Heading2,
    isData: false,
    defaultSettings: () => ({
      id: nextId('b'),
      type: 'heading',
      text: 'Section heading',
    }),
  },
  {
    type: 'paragraph',
    label: 'Paragraph',
    group: 'Display',
    icon: AlignLeft,
    isData: false,
    defaultSettings: () => ({
      id: nextId('b'),
      type: 'paragraph',
      text: 'Explanatory text.',
    }),
  },
];

export const ROLE_COMPAT = {
  name: ['text'],
  email: ['email'],
  phone: ['phone'],
  resume: ['file'],
  platforms: ['checkbox_group'],
};

export function findFieldType(type) {
  return FIELD_TYPES.find((t) => t.type === type);
}
