// HR design system — color accent tokens.
// One source of truth for the indigo/emerald/amber/violet/rose/sky family.
// Used by StatCard, SectionCard, SectionTitle, EmptyState, StatusBadge.

export const ACCENTS = {
    indigo: {
        dot: 'bg-indigo-500',
        iconFlat: 'text-indigo-600',
        iconBg: 'bg-indigo-50',
        iconBgSolid: 'bg-gradient-to-br from-indigo-500 to-indigo-600 shadow-md shadow-indigo-500/30',
        iconColorOnSolid: 'text-white',
        cardTint: 'bg-gradient-to-br from-indigo-100 to-indigo-50',
        cardTintSubtle: 'bg-gradient-to-br from-indigo-50/60 via-white to-white',
        border: 'border-indigo-200',
        borderSubtle: 'border-indigo-100',
        label: 'text-indigo-800',
        shadow: 'hover:shadow-indigo-200/60',
        ring: 'focus-visible:ring-indigo-500',
    },
    emerald: {
        dot: 'bg-emerald-500',
        iconFlat: 'text-emerald-600',
        iconBg: 'bg-emerald-50',
        iconBgSolid: 'bg-gradient-to-br from-emerald-500 to-emerald-600 shadow-md shadow-emerald-500/30',
        iconColorOnSolid: 'text-white',
        cardTint: 'bg-gradient-to-br from-emerald-100 to-emerald-50',
        cardTintSubtle: 'bg-gradient-to-br from-emerald-50/60 via-white to-white',
        border: 'border-emerald-200',
        borderSubtle: 'border-emerald-100',
        label: 'text-emerald-800',
        shadow: 'hover:shadow-emerald-200/60',
        ring: 'focus-visible:ring-emerald-500',
    },
    amber: {
        dot: 'bg-amber-500',
        iconFlat: 'text-amber-600',
        iconBg: 'bg-amber-50',
        iconBgSolid: 'bg-gradient-to-br from-amber-500 to-orange-500 shadow-md shadow-amber-500/30',
        iconColorOnSolid: 'text-white',
        cardTint: 'bg-gradient-to-br from-amber-100 to-amber-50',
        cardTintSubtle: 'bg-gradient-to-br from-amber-50/60 via-white to-white',
        border: 'border-amber-200',
        borderSubtle: 'border-amber-100',
        label: 'text-amber-800',
        shadow: 'hover:shadow-amber-200/60',
        ring: 'focus-visible:ring-amber-500',
    },
    violet: {
        dot: 'bg-violet-500',
        iconFlat: 'text-violet-600',
        iconBg: 'bg-violet-50',
        iconBgSolid: 'bg-gradient-to-br from-violet-500 to-fuchsia-500 shadow-md shadow-violet-500/30',
        iconColorOnSolid: 'text-white',
        cardTint: 'bg-gradient-to-br from-violet-100 to-violet-50',
        cardTintSubtle: 'bg-gradient-to-br from-violet-50/60 via-white to-white',
        border: 'border-violet-200',
        borderSubtle: 'border-violet-100',
        label: 'text-violet-800',
        shadow: 'hover:shadow-violet-200/60',
        ring: 'focus-visible:ring-violet-500',
    },
    rose: {
        dot: 'bg-rose-500',
        iconFlat: 'text-rose-600',
        iconBg: 'bg-rose-50',
        iconBgSolid: 'bg-gradient-to-br from-rose-500 to-rose-600 shadow-md shadow-rose-500/30',
        iconColorOnSolid: 'text-white',
        cardTint: 'bg-gradient-to-br from-rose-100 to-rose-50',
        cardTintSubtle: 'bg-gradient-to-br from-rose-50/60 via-white to-white',
        border: 'border-rose-200',
        borderSubtle: 'border-rose-100',
        label: 'text-rose-800',
        shadow: 'hover:shadow-rose-200/60',
        ring: 'focus-visible:ring-rose-500',
    },
    sky: {
        dot: 'bg-sky-500',
        iconFlat: 'text-sky-600',
        iconBg: 'bg-sky-50',
        iconBgSolid: 'bg-gradient-to-br from-sky-500 to-sky-600 shadow-md shadow-sky-500/30',
        iconColorOnSolid: 'text-white',
        cardTint: 'bg-gradient-to-br from-sky-100 to-sky-50',
        cardTintSubtle: 'bg-gradient-to-br from-sky-50/60 via-white to-white',
        border: 'border-sky-200',
        borderSubtle: 'border-sky-100',
        label: 'text-sky-800',
        shadow: 'hover:shadow-sky-200/60',
        ring: 'focus-visible:ring-sky-500',
    },
    pink: {
        dot: 'bg-pink-500',
        iconFlat: 'text-pink-500',
        iconBg: 'bg-pink-50',
        iconBgSolid: 'bg-gradient-to-br from-pink-500 to-rose-500 shadow-md shadow-pink-500/30',
        iconColorOnSolid: 'text-white',
        cardTint: 'bg-gradient-to-br from-pink-100 to-pink-50',
        cardTintSubtle: 'bg-gradient-to-br from-pink-50/60 via-white to-white',
        border: 'border-pink-200',
        borderSubtle: 'border-pink-100',
        label: 'text-pink-800',
        shadow: 'hover:shadow-pink-200/60',
        ring: 'focus-visible:ring-pink-500',
    },
    slate: {
        dot: 'bg-slate-500',
        iconFlat: 'text-slate-600',
        iconBg: 'bg-slate-100',
        iconBgSolid: 'bg-gradient-to-br from-slate-500 to-slate-600 shadow-md shadow-slate-500/30',
        iconColorOnSolid: 'text-white',
        cardTint: 'bg-slate-50',
        cardTintSubtle: 'bg-white',
        border: 'border-slate-200',
        borderSubtle: 'border-slate-100',
        label: 'text-slate-700',
        shadow: 'hover:shadow-slate-200/60',
        ring: 'focus-visible:ring-slate-500',
    },
};

export function getAccent(name) {
    return ACCENTS[name] || ACCENTS.indigo;
}
